export enum IUpdateStatus {
  UPDATE_NOT_ALLOWED = "UPDATE_NOT_ALLOWED",
  TRANSACTION_INVALID = "TRANSACTION_INVALID",
  TRANSACTION_VALID = "TRANSACTION_VALID",
  UPDATE_COMPLETED = "UPDATE_COMPLETED",
}
